### PR TITLE
 feat(ci): add CI for bootstrap 

### PR DESCRIPTION
**Pull request by sschmittsva**
Run `make bootstrap` in CI.

### CODE REVIEW

**Comment by FalcoSuessgott** [comment]
can u rebase pls and make the commit msg conventional, pls?

**Comment by sschmittsva** [comment]
done

**Comment by FalcoSuessgott** [comment]
I think we have to add:

```bash
SHELL := /bin/bash

.PHONY: bootstrap
bootstrap: deps ## boostrap cluster
	source  .envrc
	terraform init
	terraform apply -target=module.kubernetes -auto-approve
	terraform apply -auto-approve
```

to the makefile. can you try?

**Comment by sschmittsva** [comment]
`cat: .vault_token: No such file or directory`

:chicken: :egg: ?

**Comment by FalcoSuessgott** [comment]
fixed in #24

**Pull request closed without merging**
